### ISSUE TITLE
Consider using git submodule to include OpexTemplate

### ISSUE THREAD

**Issue by ArwynFr** [team-gsri/Orion#11]
Git submodule allows to sync a repository directory to another repository.
Any update on the other repository will be accessible from the current repo.

https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by ImplicitDeny** [comment]
It is an interesting idea, however the intricated nature of A3 missions might be a serious obstacle : some files have to be copied as-is, some have to be left appart, some have to be merged in a specific way.

I'm afraid that adding and finely configuring such a system would be quite tiring, for not that much help.

However I have no experience in this : feel free to try it out on a dedicated branch.

**Comment by ArwynFr** [comment]
Looks like we'll be moving Opex to a mod, so submodule is not needed anymore.
