### ISSUE TITLE
Deactivate Ace view distance limiter

### ISSUE THREAD

**Issue by ArwynFr** [team-gsri/Orion#13]

**Comment by ImplicitDeny** [comment]
I removed absolutely all mission-set CBA settings. GSRI can rely exclusively on server defined parameters. However, the mission file does not seem to be affected. Consequently I'm unsure of where mission settings are stored.

**Comment by ArwynFr** [comment]
@ImplicitDeny can you confirm this issue can be closed ?

**Comment by ImplicitDeny** [comment]
Did you have any problem with view distance recently ? I was probably waiting for feedback on dev before closing this, but has never received any. If all is ok, then yes, can be closed
