### ISSUE TITLE
Split fn_populateSheds in 3 files

### ISSUE THREAD

**Issue by ArwynFr** [team-gsri/Orion#16]
>> Shouldn't you make 3 different files for each type ?

> I should, and I will. However these scripts are being rewritten due to the occupation system feature dev. Once polished I will replace these with the new ones.

_Originally posted by @ImplicitDeny in https://github.com/team-gsri/Orion/pull/15_

**Comment by ImplicitDeny** [comment]
Same as #17 : wontfix
