### ISSUE TITLE
Rewrite stuff as libraries or functions

### ISSUE THREAD

**Issue by ArwynFr** [team-gsri/Orion#2]
> EOS must be at mission root, preslots will be rewritten and built as functions, and airdrop must be at mission root too. This is a behaviour stabiolization update, not a full rewrite ;)

_Originally posted by @ImplicitDeny in https://github.com/team-gsri/Orion/pull/1#issuecomment-504474517_

**Comment by ImplicitDeny** [comment]
There is a need for internal discussion about the modification of preslots. What to add, remove, change, etc.
See Discord, #interv
