### ISSUE TITLE
Rework file structure

### ISSUE THREAD

**Issue by ImplicitDeny** [team-gsri/Orion#27]
@ArwynFr after merging all remaining fixes and features from dev to master, shouldn't we change the way that Orion is hosted on Github on the same model than Tembelan is ?

**Comment by ArwynFr** [comment]
Yes, it would allow not to embed some useless files such as .github directory content

**Comment by ImplicitDeny** [comment]
Do you mean, embedding in the PBO file ? It should be on the exclusion list by default, at least for the integrated builder. I have no idea on how Mikero behave on this point.

**Comment by ArwynFr** [comment]
It's easier to have mission content in a directory and non mission content outside, rather than maintaining a blacklist of files.
BTW, I'm relying on armake2 to rapify the mission and pack to pbo.

**Comment by ImplicitDeny** [comment]
'kay then I'm waiting for your feedback on the current dev version (whether it is loading properly or not), and if all is okay we will merge dev and reorganize this repo
