### ISSUE TITLE
Add community elements

### ISSUE THREAD

**Issue by ArwynFr** [team-gsri/Orion#3]
https://github.com/team-gsri/Orion/community

We should, at the very least add a README and select a License quickly

**Comment by ImplicitDeny** [comment]
I suggest relying on APL for the licence : https://www.bohemia.net/community/licenses/arma-public-license
It allows rework, fork, modification, etc, under some conditions such as Attribution.

About the readme... What about copy-pasting the repo recap ? I have no idea about what to add in this file.

**Comment by ArwynFr** [comment]
Usually you give a detailed description, how to get help, how to contribute, how to install/use and a pointer to legal stuff such as license

**Comment by ImplicitDeny** [comment]
Waiting for @ArwynFr 's review on PR #14 to close this

**Comment by ImplicitDeny** [comment]
Added with https://github.com/team-gsri/Orion/commit/eacd3b3105d8d41b2ca24885e2bcb148769845ef
