### ISSUE TITLE
Add Zeus protection

### ISSUE THREAD

**Issue by ImplicitDeny** [team-gsri/Orion#4]
Using server-side mission config storage of Steam UID is a way to do so.

A faster and cleaner way to do it is to rely on `squadParams` since it includes the Unit name, which is unique, and doesn't seems to be stored on local computer.

**Comment by ImplicitDeny** [comment]
`SquadParams` is not dedicated to A3 Units, any kind of hosted squadXML would be impossible to differenciate from a proper Unit. Consequently, Zeus protection cannot rely on squadParams.

However, sarogahtyp from BI forum suggested to add a new command allowing to (un)register a new UID in `profileNamespace` of the server. Such a command would be allowed only for already registered players or of loggedAdmin.

**Comment by ArwynFr** [comment]
Perhaps registering an UID should be limited to loggedAdmins and not cooptation

**Comment by ArwynFr** [comment]
GSRI Arma 3 unit is currently open for anyone to register, so this is another reason why relying on it is not a secure solution.

**Comment by ImplicitDeny** [comment]
Deprecated issue, switching to GZM in a close future.
