### ISSUE TITLE
Heli spawner "dummy" bug

### ISSUE THREAD

**Issue by ImplicitDeny** [team-gsri/Orion#43]
The helicopter spawner onboard Normandie seems to be stuck by detecting an object named "dummy" on the hangar helipad, which is not removable nor replacable with a proper chopper.

**Comment by ArwynFr** [comment]
Was not fixed by #44

**Comment by ArwynFr** [comment]
Should be fixed by team-gsri/GSRI-Opex#70

**Comment by ArwynFr** [comment]
Confirmed fixed with OPEX
